version: '3.1'

services:
 
  db:
    image: mariadb:10.5
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: db
    volumes:
      - db:/var/lib/mysql

  php:
    build:
      context: ./php-fpm
      dockerfile: dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./nginx/public:/var/www/localhost.localdomain

  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-config:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/public:/var/www/localhost.localdomain
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot

volumes:
  db:
#  web: